### ISSUE TITLE
Berikan Konfirmasi Yes/No jika belum semua senjata didaftarkan

### ISSUE THREAD

**Issue by pascalalfadian** [LaserGunV2/CommandCenter#13]
Saat tombol "Mulai Latihan" ditekan, periksa apakah setiap prajurit sudah terassign dengan senjata. Jika belum semua, tampilkan konfirmasi:

> Belum semua prajurit memiliki senjata. Apakah ingin tetap dilanjutkan?

Jika jawabannya "Yes", tetap dilanjutkan. Jika "No", dibatalkan.

**Comment by yohansugiyo** [comment]
Ko apakah saya perlu memberi tahu prajurit no berapa saja yang belum terassign?

**Comment by pascalalfadian** [comment]
Ga usah, yang penting diingatkan aja. thanks.
