### ISSUE TITLE
Installer untuk CommandCenter

### ISSUE THREAD

**Issue by pascalalfadian** [LaserGunV2/CommandCenter#15]
Yohan, seperti di email, perlu dibuat installer untuk CommandCenter. Sepertinya VS Express tidak dukung, jadi harus pakai yang open source. Coba, apakah bisa dengan menggunakan:
- Wix (http://wixtoolset.org/)
- NSIS (http://nsis.sourceforge.net/Main_Page)

Sepertinya lebih menjanjikan yang Wix, karena yang NSIS sudah tidak diupdate berbulan-bulan.

Trims.

**Comment by yohansugiyo** [comment]
Ok ko.
Tapi kita butuh .exe atau .msi ko?
Saya dapet satu app lagi namanya INNO Setup sesuai referensi
http://stackoverflow.com/questions/458900/free-software-for-windows-installers-nsis-vs-wix

**Comment by pascalalfadian** [comment]
MSI ataupun EXE tidak masalah. Yang penting bisa 1-click install, dan mudah untuk dipakai saja.
INNO Setup kalau mau coba juga boleh, kelihatannya masih diupdate sampai sekarang.

**Comment by yohansugiyo** [comment]
ok ko

2015-02-23 12:46 GMT+07:00 Pascal <notifications@github.com>:
